const pastEvents = [
  {
    image: '/static/event/bruinquest.png',
    name: 'Hack x ICPC x Cyber presents BruinQuest',
    quarter: 'Fall 2020',
    description: 'Explore a virtual UCLA campus and complete fun challenges to compete for points, prizes, and the glory of being Bruin Quest Champion!',
  },
  {
    image: '/static/event/intro.png',
    name: 'Intro to Competitive Programming',
    quarter: 'Fall 2020',
    description: 'From climbing coding leaderboards to competing in ICPC regionals to constructing clever algorithms with clever friends, the Competitive Programming journey starts here. Write your first contest solution and learn what it takes to start solving challenging and often beautiful problems!',
  },
  {
    image: '/static/event/fallgm_blank.png',
    name: 'ICPC General Meeting',
    day: 'Thu',
    date: 'Sept. 30',
    time: '7 pm - 8 pm PT',
    quarter: 'Fall 2021',
    location: 'Boelter Hall 4760',
    description: 'In-person space has filled up. Check Facebook/Discord for the Zoom link!',
    facebook: 'https://www.facebook.com/events/1805522092967093',
    discord: 'https://discord.com/channels/702801010426511373/702835998207246426',
  },
  {
    image: '/static/event/upcoming/graph.png',
    name: 'ICPC Team Kickoff',
    day: 'Sat',
    date: 'Oct. 2',
    time: '12 pm - 3 pm PT',
    quarter: 'Fall 2021',
    location: 'Engineering VI 289',
    description: "Join members of last year's Divisionals- and Worlds- qualifying ICPC teams for an ICPC practice and learn more about joining for the 2022 season!",
    // facebook: 'https://fb.me/e/ddXe8iFSC',
    discord: 'https://discord.com/channels/702801010426511373/702835998207246426',
  },
  {
    image: '/static/event/upcoming/graph.png',
    name: 'ICPC Team Tryout #1',
    day: 'Sat',
    date: 'Oct. 9',
    time: '12 pm - 3 pm PT',
    // quarter: 'Fall 2021',
    location: 'Engineering VI 289',
    description: "An individual programming contest to select some of the team members for the 2021-22 Regionals team!",
    // facebook: 'https://fb.me/e/ddXe8iFSC',
    discord: 'https://discord.com/channels/702801010426511373/702835998207246426',
  }
];

const allEvents = [
  {
    image: '/static/event/intro.png',
    name: 'Beginner Competitive Programming',
    quarter: 'Fall',
    description: 'Continue your journey into competitive programming with Beginner CP. Continuing on from Intro CP, we explore slightly more advanced yet beginner-friendly themes in competitive programming. Whether you are completely new to CP, an expert looking for a quick review, or just an algorithm and problem-solving enthusiast, we promise you will find the workshops interesting and fun!',
  },
  {
    image: '/static/event/interview.png',
    name: 'Interview Crash Course (Interview Track)',
    quarter: 'Fall/Winter',
    description: 'Worried about your upcoming coding interview? Don’t worry, we got you covered! ACM ICPC is hosting a crash course that’ll give you the data structure and algorithm knowledge you’ll need to ace your next technical interview. Come through to hone your skills and get a head start on your CS career!',
  },
  {
    image: '/static/event/advanced.png',
    name: 'Advanced Training',
    quarter: 'Fall',
    description: 'An advanced workshop to help learn and practice advanced algorithms, data structures, and problem solving skills. Focus of the workshop will be preparing for the ICPC competition, but the workshop is open to anyone interested!',
  },
  {
    image: '/static/event/codesprint.png',
      name: 'CodeSprintLA',
    quarter: 'Spring',
    description: 'CodeSprintLA is UCLA’s own Competitive Programming Competition organized by ACM ICPC. Competitive Programming is the activity (some call it a sport!) of writing programs to solve computational problems. You must be clever with your algorithm to solve the program in a given time limit. Individual or teams compete to solve the most problems!',
  },
];

const Seniors = [
  {
    image: '/static/member/jz.png',
    name: 'Jacob Zhang',
    position: 'President',
    description: 'I’m a 4th year Math/CS double major interested in all things math and CS. I enjoy running, rock climbing, and learning Chinese. I’ve never been outside of the country, but I have visited over 30 US states.',
    funFacts: {
      'ice cream': 'Handel’s Graham Central Station',
      professor: 'Eggert',
      editor: 'VSCode + Vim keybindings',
      'favorite TV show': 'Queen’s Gambit',
    },
  },
  {
    image: '/static/member/ag.png',
    name: 'Ana Gu',
    position: 'Officer',
    description: 'Hello. I’m Ana. I am a fourth year majoring in CS. In my free time, I\m usually playing my switch and watching TV. Hit me up if you’re into carnivorous plants and/or houseplants.',
    funFacts: {
      'ice cream': 'Ruby Chocolate',
      professor: 'Smallberg',
      editor: 'Emacs/Pycharm',
      'favorite TV show': 'Brooklyn 99',
    },
  },
  {
    image: '/static/member/an.png',
    name: 'Alvin Nguyen',
    position: 'Officer',
    description: 'Hi, I’m Alvin. I’m a 4th year CS major + math minor, and I’ve helped teach ICPC workshops for almost 3 years now. Outside of tech, I enjoy playing Minecraft, and I also do a little bit of running.',
    funFacts: {
      'ice cream': 'Chocolate',
      professor: 'Smallberg',
      editor: 'VS Code',
      'favorite TV show': 'The Boys',
    },
  },
  {
    image: '/static/member/rn.png',
    name: 'Rohit Nema',
    position: 'Officer',
    description: 'Hi! I’m Rohit, a 4th year Computer Science and Math major. I’m currently involved in Cryptography research and trying to dip my feet in competitive programming. I like to watch anime and play basketball.',
    funFacts: {
      'ice cream': 'Mint Chocolate Chip',
      professor: 'Eggert',
      editor: 'Vim',
      'favorite TV show': 'Re:Zero',
    },
  },
  {
    image: '/static/member/bl.png',
    name: 'Bill Liu',
    position: 'Officer',
    description: 'Hi there! I’m Bill, a fourth-year CS major interested in iOS development and competitive programming! At ICPC, I used to lead Interview Track, and now I’m involved with events like Bruin Quest! I also enjoy fencing, painting, chess, and digital card games!',
    funFacts: {
      'ice cream': 'Mango/Peach',
      professor: 'Eggert',
      editor: 'Emacs',
      'favorite TV show': 'Mythic Quest',
    },
  },
  {
    image: '/static/member/ak.png',
    name: 'Arjun Kallapur',
    position: 'Officer',
    description: 'Hi I’m Arjun and I am a 4th year CS major! I’m super passionate about teaching and learning new things. Catch me gardening, listening to pop music, and trying to (and mostly failing to) cook.',
    funFacts: {
      'ice cream': 'Chocolate',
      professor: 'Eggert',
      editor: 'VS Code',
      'favorite TV show': 'The Bachelor',
    },
  },
  {
    image: '/static/member/aj.png',
    name: 'Arihant Jain',
    position: 'Officer',
    description: '4th year CS Major originally from NJ 1/3 of the ICPC team representing UCLA. Big fan of Air Bud, Rocket League, and spicy food',
    funFacts: {
      'ice cream': 'Butter Pecan',
      professor: 'Nachenberg',
      editor: 'VS Code',
      'favorite TV show': 'Barry',
    },
  },
  {
    image: '/static/member/rd.png',
    name: 'Reiya Downs',
    position: 'Officer',
    description: 'Hi! :) I’m Reiya, and I’m a a fourth year Math of Computation major who loves rational fiction, TV, dancing, and learning to draw! I also know 1 card trick, and if you’re lucky I’ll show you ;)',
    funFacts: {
      'ice cream': 'Double Peanut Butter Chip',
      professor: 'Jon Eyolfson',
      editor: 'Emacs',
      'favorite TV show': 'Banana Fish',
    },
  },
  {
    image: '/static/member/ns.png',
    name: 'Nikil Selvam',
    position: 'Advisor',
    description: 'Hey! I’m Nikil, a 4th year majoring in cs & math. i hail from qatar (bonus points if you know this desert in the middle east!). badminton player, ml enthusiast, keyboardist, algorithms junkie, factorio novice, and a die-hard roger federer fan! former icpc prez, now advisor :)',
    funFacts: {
      'ice cream': 'Olive Oil',
      professor: 'Darwiche',
      editor: 'VS Code',
      'favorite TV show': 'The Crown',
    },
  },
]

const members = [
  {
    image: '/static/member/rl.png',
    name: 'Robert Lee',
    position: 'President',
    description: 'Hi! I’m Robert, a 2nd year studying Math of Computation and Aerospace Engineering from San Diego. I love competitive programming and teaching algorithms! My hobbies include working on never-ending projects and gaming.',
    funFacts: {
      'ice cream': 'Vietnamese Rocky Road',
      professor: 'Taira',
      editor: 'VS Code',
      language: 'C++',
      course: 'CS 35L',
      'favorite TV show': 'Community',
    },
  },
  {
    image: '/static/member/jl.png',
    name: 'Justin Li',
    position: 'Vice President',
    description: 'I’m Justin, a third year Computer Science major! I like doing competitive programming and solving puzzles, but I also really enjoy doing non-techy things like cooking, reading, or hiking. Always looking to try something new!',
    funFacts: {
      'ice cream': 'Cookies and Cream',
      professor: 'Smallberg',
      editor: 'CodeBlocks',
      language: 'C++',
      course: 'Filet Mignon',
      'favorite TV show': 'I don’t watch TV :)',
    },
  },
  {
    image: '/static/member/rs.png',
    name: 'Rishi Sankar',
    position: 'Officer',
    description: 'Hi! I’m Rishi, a 3rd year from the Bay Area. This year I’ve been involved with Codesprint and team practices with ICPC. In my free time I enjoy watching movies, going out to eat, and playing table tennis.',
    funFacts: {
      'ice cream': 'Cookies and Cream',
      professor: 'Eggert',
      editor: 'VS Code',
      language: 'Java',
      course: 'CS 132',
      'favorite TV show': 'the big bang theory',
    },
  },
  {
    image: '/static/member/tx.png',
    name: 'Tony Xia',
    position: 'Officer',
    description: 'I’m a third year CS & applied math double major interested in CP, math, and ML. All of these are math-heavy, so I really enjoy playing the violin to relax, as it only requires me to count to 4 (or 6 in rarer cases).',
    funFacts: {
      'ice cream': 'Coffee or Oreo',
      professor: 'Eggert',
      editor: 'VS Code',
      language: 'Python',
      course: 'CS 188 Deep Learning for Computer Vision',
      'favorite TV show': 'Boba Fett',
    },
  },
  {
    image: '/static/member/ss.png',
    name: 'Saarthak Sharma',
    position: 'Officer',
    description: 'I am a second-year CS Major at UCLA. I am relatively new to competitive programming but am extremely interested and trying my best to be a part of the great ACM ICPC community.',
    funFacts: {
      'ice cream': 'Chocolate Chip',
      professor: 'Reinman',
      editor: 'VS Code',
      langauge: '',
      course: '',
      'favorite TV show': 'Breaking Bad',
    },
  },
  {
    image: '/static/member/kc.png',
    name: 'Katie Chang',
    position: 'Officer',
    description: 'heyo this is kt! I am currently a third year cs major who is interested in ML, CV, bothering my friends about my cat KB, and bothering my cat :") come talk to me to get bothered uwu',
    funFacts: {
      'ice cream': 'Fudge Brownie ',
      professor: 'Smallberg',
      editor: 'Sublime. Always. Sometimes nano/vim if I’m feeling frisky',
      language: 'C++',
      course: 'all the CS188s <3',
      'favorite TV show': 'umm can’t decide between Solar Opposites and the Blacklist',
    },
  },
  {
    image: '/static/member/lw.png',
    name: 'Lenny Wu',
    position: 'Officer',
    description: 'I’m Lenny, a 3rd-year CS and Applied Math major. I like to cook, shoot photos, play piano, and read. You’ll also catch me running or lifting weights! :^)',
    funFacts: {
      'ice cream': 'Peanut Butter Banana',
      professor: 'my boi JONATHAN KAO',
      editor: 'VS Code',
      language: 'Python',
      course: 'ECE C147 neural networks and deep learning',
      'favorite TV show': 'WORLDSTAR HIPHOP',
    },
  },
  {
    image: '/static/member/lj.png',
    name: 'Lucas Jeong',
    position: 'Officer',
    description: 'hi im lucas',
    funFacts: {
      'ice cream': 'strawberry',
      professor: 'sherstov',
      editor: 'vscode + neovim',
      language: 'java',
      course: 'cs 181',
      'favorite TV show': 'i dont watch tv',
    },
  },
  {
    image: '/static/member/nv.png',
    name: 'Neil Vaishampayan',
    position: 'Officer',
    description: 'Hi! I’m Neil, a 3rd year CS major from the Bay Area interested in compilers and ML. In my free time, I like to watch soccer, play the horn, and play video games.',
    funFacts: {
      'ice cream': 'Mint Chocolate Chip',
      professor: 'Palsberg',
      editor: 'PyCharm',
      language: 'Python',
      course: 'CS 132',
      'favorite TV show': 'Kenobi',
    },
  },
  {
    image: '/static/member/cc.png',
    name: 'Carson Cox',
    position: 'Officer',
    description: 'Hello! My name is Carson and I am a second year Computer Science and Applied Math major. This quarter I am leading beginner track and helping out with CodeSprint LA preparation. In my free time I like to rock climb, watch anime, and game. I’ve climbed a V9 in a gym before, my favorite animes are Hunter x Hunter, One Piece, and Naruto (I am caught up in all three), and my favorite games are Minecraft, Pokemon, and Smash. I also like to slack line, get food in Westwood, and do hand-stands :).',
    funFacts: {
      'ice cream': 'Vanilla',
      professor: 'Eggert',
      editor: 'Emacs for text editing and Xcode for ide',
      language: 'C++',
      course: 'CS 35L',
      'favorite TV show': 'Hunter x Hunter',
    },
  },
  {
    image: '/static/member/is.png',
    name: 'Illia Shkirko',
    position: 'Officer',
    description: 'Hi! I’m Illia Shkirko, a first-year student majoring in Computer Science and Engineering! I joined ACM ICPC in Fall 2021 and have been involved in Beginner and Interview Tracks, and CodeSprint preparation. I enjoy rock-climbing, solving Physics problems, and watching Netflix!',
    funFacts: {
      'ice cream': 'Chocolate',
      professor: 'Randy Fallows',
      editor: 'CodeBlocks',
      language: 'C++',
      course: 'Physics 1BH',
      'favorite TV show': 'Dynasty',
    },
  },
  {
    image: '/static/member/rt.png',
    name: 'Ryan Tjoa',
    position: 'Officer',
    description: 'I’m a second year computer science major from Seattle. I was a part of Interview Track in winter, and am helping out with Beginner Track now.',
    funFacts: {
      'ice cream': 'Cookie Dough',
      professor: 'Millstein',
      editor: 'VS Code',
      language: 'Python',
      course: 'CS 231',
      'favorite TV show': 'Squid Game',
    },
  },
  {
    image: '/static/member/sn.png',
    name: 'Suhas Nagar',
    position: 'Officer',
    description: 'Hi! I’m Suhas, a 1st year CS Major from the Bay Area. I’m involved in Interview Track and Codesprint. In my free time, you can usually find me playing video games (I’m a big fan of Hollow Knight), trying to write my own rap battles, or playing basketball at Hitch :)',
    funFacts: {
      'ice cream': 'Cookies and Cream',
      professor: 'Smallberg',
      editor: 'IntelliJ IDEA',
      language: 'Java',
      course: 'CS 32',
      'favorite TV show': 'Arcane',
    },
  },
  {
    image: '/static/member/ad.png',
    name: 'Arvin Ding',
    position: 'Officer',
    description: 'Hi! I’m a first year CS major. I like math, Valorant, competitive programming, sushi, and shark tank. I want do a triathlon and create a startup at some point.',
    funFacts: {
      'ice cream': 'mango',
      professor: 'Igor Pak!',
      editor: 'Eclipse',
      language: 'Java',
      course: 'CS 35L',
      'favorite TV show': 'Ping Pong The Animation!!!',
    },
  },
  {
    image: '/static/member/jh.png',
    name: 'Jason Huang',
    position: 'Officer',
    description: 'Hi! I’m a first-year math major with an interest in ML. You can usually catch me playing piano at Covel. I also like to lift weights and watch anime (big fan of Attack on Titan and Studio Ghibli movies).',
    funFacts: {
      'ice cream': 'Cotton candy',
      professor: 'Gieseker',
      editor: 'Sublime Text',
      language: 'Java',
      course: 'Japan 50 ',
      'favorite TV show': 'Attack on Titan',
    },
  },
];

export { allEvents, members, pastEvents };
